/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import com.nonograms.core.Library;
import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
  @Test
  public void testSomeLibraryMethod() {
    Library classUnderTest = new Library();
    assertTrue("someLibraryMethod should return 'true'", true);
  }
}
