/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import com.nonograms.core.Library;
import org.junit.Test;
import java.nio.file.Path;
import java.nio.file.Paths;

public class LibraryTest {
  @Test
  public void testSomeLibraryMethod() throws Exception {

    Path currentRelativePath = Paths.get("");
    String s = currentRelativePath.toAbsolutePath().toString();
    System.out.println("Current relative path is: " + s);
    
    Library.main(new String[]{"src/test/resources/g_vinyl_1.jpg", "src/test/resources/out.jpg", "jpg"});
  }
}
